# Generated by Django 5.2 on 2025-08-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_alter_notificationpreference_topic_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='topic',
            field=models.CharField(choices=[('topic_1', 'topic_1'), ('topic_2', 'topic_2'), ('topic_3', 'topic_3'), ('topic4', 'topic4')], max_length=50),
        ),
    ]
