# Generated by Django 5.2 on 2025-08-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_alter_notificationpreference_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='topic',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth')], max_length=50),
        ),
    ]
